In [1]:
import osmnx as ox
import pandas as pd
import json

from utils import *

## Calculate congestion of network for off-peak

In [2]:
G = ox.save_load.load_graphml(filename="Singapore_drive.graphml")
edges = ox.graph_to_gdfs(G, nodes=False, edges=True)

print(type(G))

f = open("data/traffic/Sun_12am_off.json", "r").read()
x = json.loads(f)
speed_bands = pd.DataFrame.from_dict(x, orient='columns')
process_speed_band(speed_bands)
calculate_congestion(G, edges, speed_bands)

edges.head()

<class 'networkx.classes.multidigraph.MultiDiGraph'>

/home/orionstar25/Semester-8-Major-Project/Open Street Maps/Numerical Experiments - Temporal/utils.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['MaximumSpeed'][i] = '80'

,u,v,key,osmid,oneway,name,highway,maxspeed,length,travel_time,Location,geometry,observed_speed,capacity
0,1820000257,1865254946,0,174765824,True,Tampines Avenue 8,tertiary,60.0,14.248,0.85488,"(1.3565805, 103.9326163, 1.3566943, 103.9326752)","LINESTRING (103.93262 1.35658, 103.93268 1.35669)",36.5,5
1,1820000257,4662056865,0,587044201,True,Tampines Avenue 5,primary,60.0,27.282,1.63692,"(1.3565805, 103.9323996, 1.3566955, 103.9326163)","LINESTRING (103.93262 1.35658, 103.93240 1.35670)",36.5,9
2,3874553858,6995781882,0,384254693,False,Fidelio Street,tertiary,40.0,20.740,1.8666,"(1.3191823, 103.9212368, 1.3192215, 103.9214192)","LINESTRING (103.92124 1.31918, 103.92142 1.31922)",29,8
3,3874553858,3874553861,0,384254631,True,Fidelio Street,tertiary,40.0,15.191,1.3671900000000001,"(1.3191111, 103.9211207, 1.3191823, 103.9212368)","LINESTRING (103.92124 1.31918, 103.92112 1.31911)",29,6
4,1820000259,245190289,0,170861145,True,Tampines Avenue 8,tertiary,60.0,13.573,0.8143800000000001,"(1.3565404, 103.9326858, 1.3566471, 103.9327451)","LINESTRING (103.93275 1.35665, 103.93269 1.35654)",37.75,5

In [3]:
make_net_tntp(edges, 'data/Singapore_net_off.tntp')

In [4]:
ox.save_load.save_graph_shapefile(G, filename='off')

## Calculate congestion of network for mod-peak

In [5]:
G = ox.save_load.load_graphml(filename="Singapore_drive.graphml")
edges = ox.graph_to_gdfs(G, nodes=False, edges=True)

print(type(G))

f = open("data/traffic/Mon_3pm_mod.json", "r").read()
x = json.loads(f)
speed_bands = pd.DataFrame.from_dict(x, orient='columns')
process_speed_band(speed_bands)
calculate_congestion(G, edges, speed_bands)

edges.head()

<class 'networkx.classes.multidigraph.MultiDiGraph'>

/home/orionstar25/Semester-8-Major-Project/Open Street Maps/Numerical Experiments - Temporal/utils.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['MaximumSpeed'][i] = '80'

,u,v,key,osmid,oneway,name,highway,maxspeed,length,travel_time,Location,geometry,observed_speed,capacity
0,1820000257,1865254946,0,174765824,True,Tampines Avenue 8,tertiary,60.0,14.248,0.85488,"(1.3565805, 103.9326163, 1.3566943, 103.9326752)","LINESTRING (103.93262 1.35658, 103.93268 1.35669)",36.5,5
1,1820000257,4662056865,0,587044201,True,Tampines Avenue 5,primary,60.0,27.282,1.63692,"(1.3565805, 103.9323996, 1.3566955, 103.9326163)","LINESTRING (103.93262 1.35658, 103.93240 1.35670)",36.5,9
2,3874553858,6995781882,0,384254693,False,Fidelio Street,tertiary,40.0,20.740,1.8666,"(1.3191823, 103.9212368, 1.3192215, 103.9214192)","LINESTRING (103.92124 1.31918, 103.92142 1.31922)",41.5,11
3,3874553858,3874553861,0,384254631,True,Fidelio Street,tertiary,40.0,15.191,1.3671900000000001,"(1.3191111, 103.9211207, 1.3191823, 103.9212368)","LINESTRING (103.92124 1.31918, 103.92112 1.31911)",39,8
4,1820000259,245190289,0,170861145,True,Tampines Avenue 8,tertiary,60.0,13.573,0.8143800000000001,"(1.3565404, 103.9326858, 1.3566471, 103.9327451)","LINESTRING (103.93275 1.35665, 103.93269 1.35654)",35.25,4

In [6]:
make_net_tntp(edges, 'data/Singapore_net_mod.tntp')

In [7]:
ox.save_load.save_graph_shapefile(G, filename="mod")

## Calculate congestion of network for high-peak

In [8]:
G = ox.save_load.load_graphml(filename="Singapore_drive.graphml")
edges = ox.graph_to_gdfs(G, nodes=False, edges=True)

print(type(G))

f = open("data/traffic/Mon_6pm_high.json", "r").read()
x = json.loads(f)
speed_bands = pd.DataFrame.from_dict(x, orient='columns')
process_speed_band(speed_bands)
calculate_congestion(G, edges, speed_bands)

edges.head()

<class 'networkx.classes.multidigraph.MultiDiGraph'>

/home/orionstar25/Semester-8-Major-Project/Open Street Maps/Numerical Experiments - Temporal/utils.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['MaximumSpeed'][i] = '80'

,u,v,key,osmid,oneway,name,highway,maxspeed,length,travel_time,Location,geometry,observed_speed,capacity
0,1820000257,1865254946,0,174765824,True,Tampines Avenue 8,tertiary,60.0,14.248,0.85488,"(1.3565805, 103.9326163, 1.3566943, 103.9326752)","LINESTRING (103.93262 1.35658, 103.93268 1.35669)",34,5
1,1820000257,4662056865,0,587044201,True,Tampines Avenue 5,primary,60.0,27.282,1.63692,"(1.3565805, 103.9323996, 1.3566955, 103.9326163)","LINESTRING (103.93262 1.35658, 103.93240 1.35670)",34,8
2,3874553858,6995781882,0,384254693,False,Fidelio Street,tertiary,40.0,20.740,1.8666,"(1.3191823, 103.9212368, 1.3192215, 103.9214192)","LINESTRING (103.92124 1.31918, 103.92142 1.31922)",26.5,7
3,3874553858,3874553861,0,384254631,True,Fidelio Street,tertiary,40.0,15.191,1.3671900000000001,"(1.3191111, 103.9211207, 1.3191823, 103.9212368)","LINESTRING (103.92124 1.31918, 103.92112 1.31911)",24,5
4,1820000259,245190289,0,170861145,True,Tampines Avenue 8,tertiary,60.0,13.573,0.8143800000000001,"(1.3565404, 103.9326858, 1.3566471, 103.9327451)","LINESTRING (103.93275 1.35665, 103.93269 1.35654)",36.5,5

In [9]:
make_net_tntp(edges, 'data/Singapore_net_high.tntp')

In [10]:
ox.save_load.save_graph_shapefile(G, filename="high")

# Make demand file (500 customers)

In [1]:
import osmnx as ox
import pandas as pd

from rtree import index
from utils import *

In [2]:
nodes_central = pd.read_pickle('data/Central_nodes.pkl')
nodes_central.drop([7330643916], inplace=True)

In [3]:
# get 10 sources from central SG
sources = nodes_central['osmid'].values[:10]
 
# get 10 targets from central SG
targets = nodes_central['osmid'].values[-10:]

In [4]:
G = ox.save_load.load_graphml(filename="Singapore_drive.graphml")
nodes = ox.graph_to_gdfs(G, nodes=True, edges=False)

In [5]:
# Fill in all nodes to find neighbours
# key: node label ,value: location
idx = index.Index()

xx = nodes['x'].astype(float)
yy = nodes['y'].astype(float)
node_id = nodes['osmid']

for node, x, y in zip(node_id, xx, yy):
    idx.insert(int(node), (x,y,x,y))

In [6]:
demands = []
for s in sources:
    for t in targets:
        demands.append([s,t])

In [7]:
make_trips_tntp(demands, "data/Singapore_trips_500.tntp")

No. of requests:  500

## Make demand file for middle mile (500 customers)

In [11]:
def bingo(sources, targets): 
    demand = []    
    count = 0
    
    for s in sources:
        for t in targets:
            orig_point = nodes[nodes['osmid'] == int(s)].geometry.values[0]
            target_point = nodes[nodes['osmid'] == int(t)].geometry.values[0]
            orig_xy = (orig_point.y, orig_point.x)
            target_xy = (target_point.y, target_point.x)

            # Find all nodes within 500m from candidate sources and destinations
            candidate_dest = find_nearest_nodes(nodes, target_xy, 500, idx)
            candidate_source = find_nearest_nodes(nodes, orig_xy, 500, idx)

            euclidean = get_length_dict(nodes, candidate_source, candidate_dest)        
            OD = modified_hybrid_search(nodes, euclidean)
            demand.append(OD)
            count += 1
            print(count, s, t)

    return demand

### Off-peak

In [12]:
demands = bingo(sources, targets)

1 233783297 571883509
2 233783297 4604559345
3 233783297 1931968496
4 233783297 4604559352
5 233783297 1931968501
6 233783297 1398079475
7 233783297 4594335734
8 233783297 1931968508
9 233783297 376619005
10 233783297 1363263487
11 626491396 571883509
12 626491396 4604559345
13 626491396 1931968496
14 626491396 4604559352
15 626491396 1931968501
16 626491396 1398079475
17 626491396 4594335734
18 626491396 1931968508
19 626491396 376619005
20 626491396 1363263487
21 5015699464 571883509
22 5015699464 4604559345
23 5015699464 1931968496
24 5015699464 4604559352
25 5015699464 1931968501
26 5015699464 1398079475
27 5015699464 4594335734
28 5015699464 1931968508
29 5015699464 376619005
30 5015699464 1363263487
31 5015699465 571883509
32 5015699465 4604559345
33 5015699465 1931968496
34 5015699465 4604559352
35 5015699465 1931968501
36 5015699465 1398079475
37 5015699465 4594335734
38 5015699465 1931968508
39 5015699465 376619005
40 5015699465 1363263487
41 5015699467 571883509
42 5015699467 4604559345
43 5015699467 1931968496
44 5015699467 4604559352
45 5015699467 1931968501
46 5015699467 1398079475
47 5015699467 4594335734
48 5015699467 1931968508
49 5015699467 376619005
50 5015699467 1363263487
51 4604559376 571883509
52 4604559376 4604559345
53 4604559376 1931968496
54 4604559376 4604559352
55 4604559376 1931968501
56 4604559376 1398079475
57 4604559376 4594335734
58 4604559376 1931968508
59 4604559376 376619005
60 4604559376 1363263487
61 626491409 571883509
62 626491409 4604559345
63 626491409 1931968496
64 626491409 4604559352
65 626491409 1931968501
66 626491409 1398079475
67 626491409 4594335734
68 626491409 1931968508
69 626491409 376619005
70 626491409 1363263487
71 626491410 571883509
72 626491410 4604559345
73 626491410 1931968496
74 626491410 4604559352
75 626491410 1931968501
76 626491410 1398079475
77 626491410 4594335734
78 626491410 1931968508
79 626491410 376619005
80 626491410 1363263487
81 1363263508 571883509
82 1363263508 4604559345
83 1363263508 1931968496
84 1363263508 4604559352
85 1363263508 1931968501
86 1363263508 1398079475
87 1363263508 4594335734
88 1363263508 1931968508
89 1363263508 376619005
90 1363263508 1363263487
91 535167001 571883509
92 535167001 4604559345
93 535167001 1931968496
94 535167001 4604559352
95 535167001 1931968501
96 535167001 1398079475
97 535167001 4594335734
98 535167001 1931968508
99 535167001 376619005
100 535167001 1363263487

In [13]:
make_trips_tntp(demands, filename="data/Singapore_trips_500_off.tntp")

No. of requests:  500

### Mod-peak

In [14]:
demands = bingo(sources, targets)

1 233783297 571883509
2 233783297 4604559345
3 233783297 1931968496
4 233783297 4604559352
5 233783297 1931968501
6 233783297 1398079475
7 233783297 4594335734
8 233783297 1931968508
9 233783297 376619005
10 233783297 1363263487
11 626491396 571883509
12 626491396 4604559345
13 626491396 1931968496
14 626491396 4604559352
15 626491396 1931968501
16 626491396 1398079475
17 626491396 4594335734
18 626491396 1931968508
19 626491396 376619005
20 626491396 1363263487
21 5015699464 571883509
22 5015699464 4604559345
23 5015699464 1931968496
24 5015699464 4604559352
25 5015699464 1931968501
26 5015699464 1398079475
27 5015699464 4594335734
28 5015699464 1931968508
29 5015699464 376619005
30 5015699464 1363263487
31 5015699465 571883509
32 5015699465 4604559345
33 5015699465 1931968496
34 5015699465 4604559352
35 5015699465 1931968501
36 5015699465 1398079475
37 5015699465 4594335734
38 5015699465 1931968508
39 5015699465 376619005
40 5015699465 1363263487
41 5015699467 571883509
42 5015699467 4604559345
43 5015699467 1931968496
44 5015699467 4604559352
45 5015699467 1931968501
46 5015699467 1398079475
47 5015699467 4594335734
48 5015699467 1931968508
49 5015699467 376619005
50 5015699467 1363263487
51 4604559376 571883509
52 4604559376 4604559345
53 4604559376 1931968496
54 4604559376 4604559352
55 4604559376 1931968501
56 4604559376 1398079475
57 4604559376 4594335734
58 4604559376 1931968508
59 4604559376 376619005
60 4604559376 1363263487
61 626491409 571883509
62 626491409 4604559345
63 626491409 1931968496
64 626491409 4604559352
65 626491409 1931968501
66 626491409 1398079475
67 626491409 4594335734
68 626491409 1931968508
69 626491409 376619005
70 626491409 1363263487
71 626491410 571883509
72 626491410 4604559345
73 626491410 1931968496
74 626491410 4604559352
75 626491410 1931968501
76 626491410 1398079475
77 626491410 4594335734
78 626491410 1931968508
79 626491410 376619005
80 626491410 1363263487
81 1363263508 571883509
82 1363263508 4604559345
83 1363263508 1931968496
84 1363263508 4604559352
85 1363263508 1931968501
86 1363263508 1398079475
87 1363263508 4594335734
88 1363263508 1931968508
89 1363263508 376619005
90 1363263508 1363263487
91 535167001 571883509
92 535167001 4604559345
93 535167001 1931968496
94 535167001 4604559352
95 535167001 1931968501
96 535167001 1398079475
97 535167001 4594335734
98 535167001 1931968508
99 535167001 376619005
100 535167001 1363263487

In [15]:
make_trips_tntp(demands, filename="data/Singapore_trips_500_mod.tntp")

No. of requests:  500

### High-peak

In [16]:
demands = bingo(sources, targets)

1 233783297 571883509
2 233783297 4604559345
3 233783297 1931968496
4 233783297 4604559352
5 233783297 1931968501
6 233783297 1398079475
7 233783297 4594335734
8 233783297 1931968508
9 233783297 376619005
10 233783297 1363263487
11 626491396 571883509
12 626491396 4604559345
13 626491396 1931968496
14 626491396 4604559352
15 626491396 1931968501
16 626491396 1398079475
17 626491396 4594335734
18 626491396 1931968508
19 626491396 376619005
20 626491396 1363263487
21 5015699464 571883509
22 5015699464 4604559345
23 5015699464 1931968496
24 5015699464 4604559352
25 5015699464 1931968501
26 5015699464 1398079475
27 5015699464 4594335734
28 5015699464 1931968508
29 5015699464 376619005
30 5015699464 1363263487
31 5015699465 571883509
32 5015699465 4604559345
33 5015699465 1931968496
34 5015699465 4604559352
35 5015699465 1931968501
36 5015699465 1398079475
37 5015699465 4594335734
38 5015699465 1931968508
39 5015699465 376619005
40 5015699465 1363263487
41 5015699467 571883509
42 5015699467 4604559345
43 5015699467 1931968496
44 5015699467 4604559352
45 5015699467 1931968501
46 5015699467 1398079475
47 5015699467 4594335734
48 5015699467 1931968508
49 5015699467 376619005
50 5015699467 1363263487
51 4604559376 571883509
52 4604559376 4604559345
53 4604559376 1931968496
54 4604559376 4604559352
55 4604559376 1931968501
56 4604559376 1398079475
57 4604559376 4594335734
58 4604559376 1931968508
59 4604559376 376619005
60 4604559376 1363263487
61 626491409 571883509
62 626491409 4604559345
63 626491409 1931968496
64 626491409 4604559352
65 626491409 1931968501
66 626491409 1398079475
67 626491409 4594335734
68 626491409 1931968508
69 626491409 376619005
70 626491409 1363263487
71 626491410 571883509
72 626491410 4604559345
73 626491410 1931968496
74 626491410 4604559352
75 626491410 1931968501
76 626491410 1398079475
77 626491410 4594335734
78 626491410 1931968508
79 626491410 376619005
80 626491410 1363263487
81 1363263508 571883509
82 1363263508 4604559345
83 1363263508 1931968496
84 1363263508 4604559352
85 1363263508 1931968501
86 1363263508 1398079475
87 1363263508 4594335734
88 1363263508 1931968508
89 1363263508 376619005
90 1363263508 1363263487
91 535167001 571883509
92 535167001 4604559345
93 535167001 1931968496
94 535167001 4604559352
95 535167001 1931968501
96 535167001 1398079475
97 535167001 4594335734
98 535167001 1931968508
99 535167001 376619005
100 535167001 1363263487

In [17]:
make_trips_tntp(demands, filename="data/Singapore_trips_500_high.tntp")

No. of requests:  500